-- Migration V8: Align all columns across legacy messages, conversations, documents, and message_sources

-- 1. Messages table alignment
ALTER TABLE messages ADD COLUMN IF NOT EXISTS token_count INT DEFAULT 0;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS model VARCHAR(100);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS latency_ms BIGINT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'user';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- 2. Conversations table alignment
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50) DEFAULT 'default';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS title VARCHAR(255) DEFAULT 'Support Session';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS mode VARCHAR(20) DEFAULT 'AI';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS assigned_agent VARCHAR(100);
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS escalation_status VARCHAR(30) DEFAULT 'NONE';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS escalation_reason TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS last_frustration_score INT DEFAULT 0;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS last_frustration_level VARCHAR(20) DEFAULT 'low';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS last_sentiment VARCHAR(20) DEFAULT 'neutral';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS last_emotion VARCHAR(30) DEFAULT 'neutral';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS last_intent VARCHAR(50);
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS last_domain VARCHAR(50);
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS call_status VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- 3. Documents table alignment
ALTER TABLE documents ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50) DEFAULT 'default';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS title VARCHAR(255) DEFAULT 'Untitled Document';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'general';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS filename VARCHAR(255);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS content_type VARCHAR(100) DEFAULT 'application/octet-stream';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS size_bytes BIGINT DEFAULT 0;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'READY';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS content_hash VARCHAR(64);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- 4. Message sources table
CREATE TABLE IF NOT EXISTS message_sources (
    id UUID PRIMARY KEY,
    message_id UUID NOT NULL,
    chunk_id UUID NOT NULL,
    similarity_score DOUBLE PRECISION NOT NULL
);
ALTER TABLE message_sources ADD COLUMN IF NOT EXISTS similarity_score DOUBLE PRECISION DEFAULT 0.0;
