/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* ── Landing Page (Teal) Tokens ── */
        "surface-container-low": "#eef5f4",
        "tertiary-fixed": "#ffdad7",
        "secondary-container": "#b8ecec",
        "on-primary": "#ffffff",
        "surface-dim": "#d4dbdb",
        "surface": "#f4fbfa",
        "on-primary-fixed": "#002020",
        "surface-tint": "#006a6a",
        "on-primary-fixed-variant": "#004f50",
        "on-tertiary": "#ffffff",
        "primary-container": "#47e5e6",
        "on-tertiary-fixed-variant": "#5c4200",
        "on-tertiary-container": "#735400",
        "surface-container-high": "#e3eae9",
        "surface-variant": "#dde4e3",
        "on-secondary-fixed": "#002020",
        "surface-container": "#e8efee",
        "secondary": "#346666",
        "outline": "#6b7a79",
        "background": "#f4fbfa",
        "outline-variant": "#bac9c9",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#3a6c6c",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#38dbdc",
        "inverse-surface": "#2b3232",
        "surface-bright": "#f4fbfa",
        "on-surface": "#161d1d",
        "on-error-container": "#93000a",
        "primary": "#006a6a",
        "on-surface-variant": "#3c4949",
        "secondary-fixed": "#b8ecec",
        "tertiary-container": "#ffc852",
        "secondary-fixed-dim": "#9dd0d0",
        "on-background": "#161d1d",
        "tertiary-fixed-dim": "#f4be49",
        "on-secondary-fixed-variant": "#194e4e",
        "inverse-primary": "#38dbdc",
        "tertiary": "#7a5900",
        "surface-container-highest": "#dde4e3",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#261900",
        "primary-fixed": "#60f8f9",
        "inverse-on-surface": "#ebf2f1",
        "on-primary-container": "#006364",
        "on-error": "#ffffff",

        /* ── Dashboard (Green) Tokens ── */
        "dash-primary": "#006948",
        "dash-primary-container": "#00855d",
        "dash-on-primary-container": "#f5fff7",
        "dash-secondary": "#006b5f",
        "dash-secondary-container": "#62fae3",
        "dash-on-secondary-container": "#007165",
        "dash-tertiary": "#9b3e3b",
        "dash-tertiary-container": "#ba5551",
        "dash-on-tertiary-container": "#fffbff",
        "dash-surface": "#f0fdfa",
        "dash-surface-bright": "#f5fbf5",
        "dash-surface-dim": "#d5dcd6",
        "dash-surface-container": "#ccfbf1",
        "dash-surface-container-low": "#eff5ef",
        "dash-surface-container-high": "#e4eae4",
        "dash-surface-container-highest": "#dee4de",
        "dash-surface-container-lowest": "#ffffff",
        "dash-surface-variant": "#dee4de",
        "dash-surface-tint": "#006c4a",
        "dash-background": "#f5fbf5",
        "dash-on-background": "#171d19",
        "dash-on-surface": "#171d19",
        "dash-on-surface-variant": "#3d4a42",
        "dash-outline": "#6d7a72",
        "dash-outline-variant": "#bccac0",
        "dash-inverse-surface": "#2c322e",
        "dash-inverse-on-surface": "#ecf2ec",
        "dash-inverse-primary": "#68dba9",
        "dash-error": "#ba1a1a",
        "dash-error-container": "#ffdad6",
        "dash-on-error": "#ffffff",
        "dash-on-error-container": "#93000a",
        "dash-primary-fixed": "#85f8c4",
        "dash-primary-fixed-dim": "#68dba9",
        "dash-on-primary-fixed": "#002114",
        "dash-on-primary-fixed-variant": "#005137",
        "dash-secondary-fixed": "#62fae3",
        "dash-secondary-fixed-dim": "#3cddc7",
        "dash-on-secondary-fixed": "#00201c",
        "dash-on-secondary-fixed-variant": "#005047",
        "dash-tertiary-fixed": "#ffdad7",
        "dash-tertiary-fixed-dim": "#ffb3ae",
        "dash-on-tertiary-fixed": "#410004",
        "dash-on-tertiary-fixed-variant": "#7f2928",
        "dash-on-primary": "#ffffff",
        "dash-on-secondary": "#ffffff",
        "dash-on-tertiary": "#ffffff",
        "dash-mint-accent": "#f0fdfa",
        "dash-status-online": "#10b981",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-xs": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      spacing: {
        "section-gap": "1rem",
        "widget-padding": "1rem",
        "stack-tight": "0.25rem",
        "bubble-gap": "0.5rem",
      },
    },
  },
  plugins: [],
}
