/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eef5f4",
        "tertiary-fixed": "#ffdea2",
        "secondary-container": "#b8ecec",
        "on-primary": "#ffffff",
        "surface-dim": "#d4dbdb",
        "surface": "#f4fbfa",
        "on-primary-fixed": "#002020",
        "surface-tint": "#006a6a",
        "on-primary-fixed-variant": "#004f50",
        "on-tertiary": "#ffffff",
        "primary-container": "#47e5e6",
        "on-tertiary-fixed-variant": "#5c4200",
        "on-tertiary-container": "#735400",
        "surface-container-high": "#e3eae9",
        "surface-variant": "#dde4e3",
        "on-secondary-fixed": "#002020",
        "surface-container": "#e8efee",
        "secondary": "#346666",
        "outline": "#6b7a79",
        "background": "#f4fbfa",
        "outline-variant": "#bac9c9",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#3a6c6c",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#38dbdc",
        "inverse-surface": "#2b3232",
        "surface-bright": "#f4fbfa",
        "on-surface": "#161d1d",
        "on-error-container": "#93000a",
        "primary": "#006a6a",
        "on-surface-variant": "#3c4949",
        "secondary-fixed": "#b8ecec",
        "tertiary-container": "#ffc852",
        "secondary-fixed-dim": "#9dd0d0",
        "on-background": "#161d1d",
        "tertiary-fixed-dim": "#f4be49",
        "on-secondary-fixed-variant": "#194e4e",
        "inverse-primary": "#38dbdc",
        "tertiary": "#7a5900",
        "surface-container-highest": "#dde4e3",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#261900",
        "primary-fixed": "#60f8f9",
        "inverse-on-surface": "#ebf2f1",
        "on-primary-container": "#006364",
        "on-error": "#ffffff",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-xs": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
